### ISSUE TITLE
Demo with examples testbed has inverted controls

### ISSUE THREAD

**Issue by MrOnlineCoder** [532235/gost.engine#62]
gost v0.4: demo_release.exe has inverted controls (A moves to right, D moves to left, same with mouse). Didn't find an option for this in settings. Is it intentional?

OS Windows 7 64bit

**Comment by 532235** [comment]
`Is it intentional?`
Yes. Perhaps need to create high-level functions like
`strafeLeft`
`turnLeft`

Not put them in gtCamera. 
gtCamera is low-level object, need keep save this property.
May be need create gtCameraFPS, i don't know.  It is not necessary now.

May be someone create functions like

    namespace util{
        void strafeLeft( gtGameObject * object, f32 speed, f32 delta ){
              f32 angle = object->getRotation().y;
              f32 sn = sin(angle / 180 * math::PI);
              f32 cs = cos(angle / 180 * math::PI);
              object->setPosition( object->getPosition() + v4f( -speed * sn * delta, 0.f, -speed * cs * delta, 0.f  ) );
        }
    }
