### ISSUE TITLE
Opening solution on other machine

### ISSUE THREAD

**Issue by MrOnlineCoder** [532235/gost.engine#65]
Please, make a short guide on how to start coding gost on a new machine (I open the solution, and receive many errors) or publish a working solution to open. The guide can be built of list of dependencies, prerequsites and project setup info.

Windows 7 64 bit
Visual Studio 2017 Community

Regards,
MrOnlineCoder

**Comment by 532235** [comment]
https://github.com/532235/gost.engine/blob/master/build/readme.txt

**Comment by 532235** [comment]
The problem was in the incorrect .vcxproj file (it did not add gtGUIButtonImpl.cpp to the Solution Explorer, but inside .vcxproj it was, which caused me confusion). 

Now the files are updated with the latest version of Visual Studio 2017, and everything should be built successfully.
