### ISSUE TITLE
[Wiki] Fix Getting Started page

### ISSUE THREAD

**Issue by MrOnlineCoder** [532235/gost.engine#67]
Wiki page [https://github.com/532235/gost.engine/wiki/Getting-Started](https://github.com/532235/gost.engine/wiki/Getting-Started) has broken link for reporting errors (where it says "here") and contains Russian text.

If you would agree, I could just remove the link and translate the Russian text.

I've created this issue because not sure if you would fix the link or no.

Regards,
MrOnlineCoder

**Comment by 532235** [comment]
ok, i agree
